/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name a more descriptive name for the action
 * @param description optional description string explaining what this action represents in your system
 */


data class ActionBlockEditable (

    /* a more descriptive name for the action */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* optional description string explaining what this action represents in your system */
    @Json(name = "description")
    val description: kotlin.String? = null

)

