/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionObject
import org.openapitools.client.models.EnvironmentObject
import org.openapitools.client.models.OrganizationObject
import org.openapitools.client.models.PdpConfigObject
import org.openapitools.client.models.ProjectObject
import org.openapitools.client.models.ResourceTypeObject
import org.openapitools.client.models.TenantObject
import org.openapitools.client.models.UserObject

import com.squareup.moshi.Json

/**
 * 
 *
 * @param organizationObject 
 * @param projectObject 
 * @param environmentObject 
 * @param pdpConfigObject 
 * @param userObject 
 * @param actionObject 
 * @param resourceTypeObject 
 * @param tenantObject 
 */


data class AuditLogObjects (

    @Json(name = "organization_object")
    val organizationObject: OrganizationObject? = null,

    @Json(name = "project_object")
    val projectObject: ProjectObject? = null,

    @Json(name = "environment_object")
    val environmentObject: EnvironmentObject? = null,

    @Json(name = "pdp_config_object")
    val pdpConfigObject: PdpConfigObject? = null,

    @Json(name = "user_object")
    val userObject: UserObject? = null,

    @Json(name = "action_object")
    val actionObject: ActionObject? = null,

    @Json(name = "resource_type_object")
    val resourceTypeObject: ResourceTypeObject? = null,

    @Json(name = "tenant_object")
    val tenantObject: TenantObject? = null

)

