/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.APIKeyOwnerType
import org.openapitools.client.models.MemberAccessObj

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param objectType 
 * @param ownerType 
 * @param orgId 
 * @param actorType 
 * @param projectId 
 * @param envId 
 */


data class AuthnMeAPIKeyRead (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "object_type")
    val objectType: MemberAccessObj,

    @Json(name = "owner_type")
    val ownerType: APIKeyOwnerType,

    @Json(name = "org_id")
    val orgId: java.util.UUID,

    @Json(name = "actor_type")
    val actorType: AuthnMeAPIKeyRead.ActorType? = ActorType.apiKey,

    @Json(name = "project_id")
    val projectId: java.util.UUID? = null,

    @Json(name = "env_id")
    val envId: java.util.UUID? = null

) {

    /**
     * 
     *
     * Values: apiKey
     */
    enum class ActorType(val value: kotlin.String) {
        @Json(name = "api_key") apiKey("api_key");
    }
}

