/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name A descriptive name for the set, i.e: 'US based employees' or 'Users behind VPN'
 * @param description an optional longer description of the set
 * @param conditions a boolean expression that consists of multiple conditions, with and/or logic.
 */


data class ConditionSetUpdate (

    /* A descriptive name for the set, i.e: 'US based employees' or 'Users behind VPN' */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* an optional longer description of the set */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* a boolean expression that consists of multiple conditions, with and/or logic. */
    @Json(name = "conditions")
    val conditions: kotlin.Any? = null

)

