/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userSet The userset that will be given permission, i.e: all the users matching this rule will be given the specified permission
 * @param permission The permission that will be granted to the userset *on* the resourceset. The permission can be either a resource action id, or `{resource_key}:{action_key}`, i.e: the \"permission name\".
 * @param resourceSet The resourceset that represents the resources that are granted for access, i.e: all the resources matching this rule can be accessed by the userset to perform the granted *permission*
 * @param isRole if True, will set the condition set rule to the role's autogen user-set.
 * @param isResource if True, will set the condition set rule to the resource's autogen resource-set.
 */


data class ConditionSetRuleCreate (

    /* The userset that will be given permission, i.e: all the users matching this rule will be given the specified permission */
    @Json(name = "user_set")
    val userSet: kotlin.String,

    /* The permission that will be granted to the userset *on* the resourceset. The permission can be either a resource action id, or `{resource_key}:{action_key}`, i.e: the \"permission name\". */
    @Json(name = "permission")
    val permission: kotlin.String,

    /* The resourceset that represents the resources that are granted for access, i.e: all the resources matching this rule can be accessed by the userset to perform the granted *permission* */
    @Json(name = "resource_set")
    val resourceSet: kotlin.String,

    /* if True, will set the condition set rule to the role's autogen user-set. */
    @Json(name = "is_role")
    val isRole: kotlin.Boolean? = false,

    /* if True, will set the condition set rule to the resource's autogen resource-set. */
    @Json(name = "is_resource")
    val isResource: kotlin.Boolean? = false

)

