/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Data source configuration - where client's should retrive data from and how they should store it
 *
 * @param url Url source to query for data
 * @param config Suggested fetcher configuration (e.g. auth or method) to fetch data with
 * @param topics topics the data applies to
 * @param dstPath OPA data api path to store the document at
 * @param saveMethod Method used to write into OPA - PUT/PATCH
 */


data class DataSourceEntry (

    /* Url source to query for data */
    @Json(name = "url")
    val url: kotlin.String,

    /* Suggested fetcher configuration (e.g. auth or method) to fetch data with */
    @Json(name = "config")
    val config: kotlin.Any? = null,

    /* topics the data applies to */
    @Json(name = "topics")
    val topics: kotlin.collections.List<kotlin.String>? = arrayListOf(),

    /* OPA data api path to store the document at */
    @Json(name = "dst_path")
    val dstPath: kotlin.String? = "",

    /* Method used to write into OPA - PUT/PATCH */
    @Json(name = "save_method")
    val saveMethod: kotlin.String? = "PUT"

)

