/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param username an email address from which to create a DEV MODE session
 */


data class DevLogin (

    /* an email address from which to create a DEV MODE session */
    @Json(name = "username")
    val username: kotlin.String

)

