/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElementsConfigRead
import org.openapitools.client.models.ElementsPermissionLevel

import com.squareup.moshi.Json

/**
 * 
 *
 * @param config 
 * @param currentPermissionLevel 
 */


data class ElementsConfigRuntimeRead (

    @Json(name = "config")
    val config: ElementsConfigRead,

    @Json(name = "current_permission_level")
    val currentPermissionLevel: ElementsPermissionLevel

)

