/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PDPConfigRead
import org.openapitools.client.models.Statistics

import com.squareup.moshi.Json

/**
 * 
 *
 * @param key A URL-friendly name of the environment (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the environment.
 * @param id Unique id of the environment
 * @param organizationId Unique id of the organization that the environment belongs to.
 * @param projectId Unique id of the project that the environment belongs to.
 * @param createdAt Date and time when the environment was created (ISO_8601 format).
 * @param updatedAt Date and time when the environment was last updated/modified (ISO_8601 format).
 * @param name The name of the environment
 * @param pdpConfigs 
 * @param stats 
 * @param description an optional longer description of the environment
 * @param customBranchName when using gitops feature, an optional branch name for the environment
 */


data class EnvironmentStats (

    /* A URL-friendly name of the environment (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the environment. */
    @Json(name = "key")
    val key: kotlin.String,

    /* Unique id of the environment */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Unique id of the organization that the environment belongs to. */
    @Json(name = "organization_id")
    val organizationId: java.util.UUID,

    /* Unique id of the project that the environment belongs to. */
    @Json(name = "project_id")
    val projectId: java.util.UUID,

    /* Date and time when the environment was created (ISO_8601 format). */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Date and time when the environment was last updated/modified (ISO_8601 format). */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* The name of the environment */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "pdp_configs")
    val pdpConfigs: kotlin.collections.List<PDPConfigRead>,

    @Json(name = "stats")
    val stats: Statistics,

    /* an optional longer description of the environment */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* when using gitops feature, an optional branch name for the environment */
    @Json(name = "custom_branch_name")
    val customBranchName: kotlin.String? = null

)

