/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name The name of the environment
 * @param description an optional longer description of the environment
 * @param customBranchName when using gitops feature, an optional branch name for the environment
 */


data class EnvironmentUpdate (

    /* The name of the environment */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* an optional longer description of the environment */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* when using gitops feature, an optional branch name for the environment */
    @Json(name = "custom_branch_name")
    val customBranchName: kotlin.String? = null

)

