/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param email The invited member's email address
 * @param role The role the member will be assigned with
 */


data class InviteCreate (

    /* The invited member's email address */
    @Json(name = "email")
    val email: kotlin.String,

    /* The role the member will be assigned with */
    @Json(name = "role")
    val role: kotlin.String

)

