/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * An enumeration.
 *
 * Values: pending,accepted,failed,canceled
 */

enum class InviteStatus(val value: kotlin.String) {

    @Json(name = "pending")
    pending("pending"),

    @Json(name = "accepted")
    accepted("accepted"),

    @Json(name = "failed")
    failed("failed"),

    @Json(name = "canceled")
    canceled("canceled");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InviteStatus) "$data" else null

        /**
         * Returns a valid [InviteStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InviteStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

