/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Labels

import com.squareup.moshi.Json

/**
 * 
 *
 * @param decisionId 
 * @param labels 
 * @param timestamp 
 * @param runId 
 * @param path 
 * @param input 
 * @param result 
 */


data class OPADecisionLog (

    @Json(name = "decision_id")
    val decisionId: java.util.UUID,

    @Json(name = "labels")
    val labels: Labels,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    @Json(name = "run_id")
    val runId: java.util.UUID? = null,

    @Json(name = "path")
    val path: kotlin.String? = null,

    @Json(name = "input")
    val input: kotlin.Any? = null,

    @Json(name = "result")
    val result: kotlin.Any? = null

)

