/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key A URL-friendly name of the organization (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the organization.
 * @param name The name of the organization, usually it's your company's name.
 * @param settings the settings for this project
 */


data class OrganizationCreate (

    /* A URL-friendly name of the organization (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the organization. */
    @Json(name = "key")
    val key: kotlin.String,

    /* The name of the organization, usually it's your company's name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* the settings for this project */
    @Json(name = "settings")
    val settings: kotlin.Any? = null

)

