/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name The name of the organization, usually it's your company's name.
 * @param settings the settings for this project
 */


data class OrganizationUpdate (

    /* The name of the organization, usually it's your company's name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* the settings for this project */
    @Json(name = "settings")
    val settings: kotlin.Any? = null

)

