/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param BACKEND_SERVICE_URL 
 * @param OPA_DECISION_LOG_INGRESS_ROUTE 
 * @param OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL 
 */


data class Pdp (

    @Json(name = "BACKEND_SERVICE_URL")
    val BACKEND_SERVICE_URL: kotlin.String,

    @Json(name = "OPA_DECISION_LOG_INGRESS_ROUTE")
    val OPA_DECISION_LOG_INGRESS_ROUTE: kotlin.String,

    @Json(name = "OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL")
    val OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL: kotlin.String

)

