/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Unique id of the elements_env
 * @param key A URL-friendly name of the elements_env (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the elements_env.
 * @param name 
 */


data class PermissionLevelRoleRead (

    /* Unique id of the elements_env */
    @Json(name = "id")
    val id: java.util.UUID,

    /* A URL-friendly name of the elements_env (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the elements_env. */
    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

