/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OPALClient
import org.openapitools.client.models.PDPContext
import org.openapitools.client.models.Pdp

import com.squareup.moshi.Json

/**
 * 
 *
 * @param opalClient 
 * @param context 
 * @param opalCommon 
 * @param pdp 
 */


data class RemoteConfig (

    @Json(name = "opal_client")
    val opalClient: OPALClient,

    @Json(name = "context")
    val context: PDPContext,

    @Json(name = "opal_common")
    val opalCommon: kotlin.Any? = null,

    @Json(name = "pdp")
    val pdp: Pdp? = null

)

