/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AttributeType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param key 
 */


data class ResourceAttributes (

    @Json(name = "type")
    val type: AttributeType,

    @Json(name = "key")
    val key: kotlin.String

)

