/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key A URL-friendly name of the action (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the action.
 * @param name The name of the action
 * @param description An optional longer description of what this action respresents in your system
 */


data class ResourceActionCreate (

    /* A URL-friendly name of the action (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the action. */
    @Json(name = "key")
    val key: kotlin.String,

    /* The name of the action */
    @Json(name = "name")
    val name: kotlin.String,

    /* An optional longer description of what this action respresents in your system */
    @Json(name = "description")
    val description: kotlin.String? = null

)

