/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionBlockRead
import org.openapitools.client.models.AttributeBlockRead

import com.squareup.moshi.Json

/**
 * 
 *
 * @param key A URL-friendly name of the resource (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the resource.
 * @param id Unique id of the resource
 * @param organizationId Unique id of the organization that the resource belongs to.
 * @param projectId Unique id of the project that the resource belongs to.
 * @param environmentId Unique id of the environment that the resource belongs to.
 * @param createdAt Date and time when the resource was created (ISO_8601 format).
 * @param updatedAt Date and time when the resource was last updated/modified (ISO_8601 format).
 * @param name The name of the resource
 * @param urn The [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) (Uniform Resource Name) of the resource
 * @param description An optional longer description of what this resource respresents in your system
 * @param actions          A actions definition block, typically contained within a resource type definition block.         The actions represents the ways you can interact with a protected resource.         
 * @param attributes Attributes that each resource of this type defines, and can be used in your ABAC policies.
 */


data class ResourceRead (

    /* A URL-friendly name of the resource (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the resource. */
    @Json(name = "key")
    val key: kotlin.String,

    /* Unique id of the resource */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Unique id of the organization that the resource belongs to. */
    @Json(name = "organization_id")
    val organizationId: java.util.UUID,

    /* Unique id of the project that the resource belongs to. */
    @Json(name = "project_id")
    val projectId: java.util.UUID,

    /* Unique id of the environment that the resource belongs to. */
    @Json(name = "environment_id")
    val environmentId: java.util.UUID,

    /* Date and time when the resource was created (ISO_8601 format). */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Date and time when the resource was last updated/modified (ISO_8601 format). */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* The name of the resource */
    @Json(name = "name")
    val name: kotlin.String,

    /* The [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) (Uniform Resource Name) of the resource */
    @Json(name = "urn")
    val urn: kotlin.String? = null,

    /* An optional longer description of what this resource respresents in your system */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /*          A actions definition block, typically contained within a resource type definition block.         The actions represents the ways you can interact with a protected resource.          */
    @Json(name = "actions")
    val actions: kotlin.collections.Map<kotlin.String, ActionBlockRead>? = null,

    /* Attributes that each resource of this type defines, and can be used in your ABAC policies. */
    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, AttributeBlockRead>? = null

)

