/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Unique id of the role assignment
 * @param user the user the role is assigned to
 * @param role the role that is assigned
 * @param tenant the tenant the role is associated with
 * @param userId Unique id of the user
 * @param roleId Unique id of the role
 * @param tenantId Unique id of the tenant
 * @param organizationId Unique id of the organization that the role assignment belongs to.
 * @param projectId Unique id of the project that the role assignment belongs to.
 * @param environmentId Unique id of the environment that the role assignment belongs to.
 * @param createdAt Date and time when the role assignment was created (ISO_8601 format).
 */


data class RoleAssignmentRead (

    /* Unique id of the role assignment */
    @Json(name = "id")
    val id: java.util.UUID,

    /* the user the role is assigned to */
    @Json(name = "user")
    val user: kotlin.String,

    /* the role that is assigned */
    @Json(name = "role")
    val role: kotlin.String,

    /* the tenant the role is associated with */
    @Json(name = "tenant")
    val tenant: kotlin.String,

    /* Unique id of the user */
    @Json(name = "user_id")
    val userId: java.util.UUID,

    /* Unique id of the role */
    @Json(name = "role_id")
    val roleId: java.util.UUID,

    /* Unique id of the tenant */
    @Json(name = "tenant_id")
    val tenantId: java.util.UUID,

    /* Unique id of the organization that the role assignment belongs to. */
    @Json(name = "organization_id")
    val organizationId: java.util.UUID,

    /* Unique id of the project that the role assignment belongs to. */
    @Json(name = "project_id")
    val projectId: java.util.UUID,

    /* Unique id of the environment that the role assignment belongs to. */
    @Json(name = "environment_id")
    val environmentId: java.util.UUID,

    /* Date and time when the role assignment was created (ISO_8601 format). */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime

)

