/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param username SSH username
 * @param privateKey SSH private key
 * @param authType 
 * @param publicKey SSH public key
 */


data class SSHAuthData (

    /* SSH username */
    @Json(name = "username")
    val username: kotlin.String,

    /* SSH private key */
    @Json(name = "private_key")
    val privateKey: kotlin.String,

    @Json(name = "auth_type")
    val authType: SSHAuthData.AuthType? = AuthType.ssh,

    /* SSH public key */
    @Json(name = "public_key")
    val publicKey: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ssh
     */
    enum class AuthType(val value: kotlin.String) {
        @Json(name = "ssh") ssh("ssh");
    }
}

