/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key A unique id by which Permit will identify the tenant. The tenant key must be url-friendly (slugified).
 * @param id Unique id of the tenant
 * @param organizationId Unique id of the organization that the tenant belongs to.
 * @param projectId Unique id of the project that the tenant belongs to.
 * @param environmentId Unique id of the environment that the tenant belongs to.
 * @param createdAt Date and time when the tenant was created (ISO_8601 format).
 * @param updatedAt Date and time when the tenant was last updated/modified (ISO_8601 format).
 * @param lastActionAt Date and time when the tenant was last active (ISO_8601 format). In other words, this is the last time a permission check was done on a resource belonging to this tenant.
 * @param name A descriptive name for the tenant
 * @param description an optional longer description of the tenant
 * @param attributes Arbitraty tenant attributes that will be used to enforce attribute-based access control policies.
 */


data class TenantRead (

    /* A unique id by which Permit will identify the tenant. The tenant key must be url-friendly (slugified). */
    @Json(name = "key")
    val key: kotlin.String,

    /* Unique id of the tenant */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Unique id of the organization that the tenant belongs to. */
    @Json(name = "organization_id")
    val organizationId: java.util.UUID,

    /* Unique id of the project that the tenant belongs to. */
    @Json(name = "project_id")
    val projectId: java.util.UUID,

    /* Unique id of the environment that the tenant belongs to. */
    @Json(name = "environment_id")
    val environmentId: java.util.UUID,

    /* Date and time when the tenant was created (ISO_8601 format). */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Date and time when the tenant was last updated/modified (ISO_8601 format). */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Date and time when the tenant was last active (ISO_8601 format). In other words, this is the last time a permission check was done on a resource belonging to this tenant. */
    @Json(name = "last_action_at")
    val lastActionAt: java.time.OffsetDateTime,

    /* A descriptive name for the tenant */
    @Json(name = "name")
    val name: kotlin.String,

    /* an optional longer description of the tenant */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Arbitraty tenant attributes that will be used to enforce attribute-based access control policies. */
    @Json(name = "attributes")
    val attributes: kotlin.Any? = null

)

