/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name A descriptive name for the tenant
 * @param description an optional longer description of the tenant
 * @param attributes Arbitraty tenant attributes that will be used to enforce attribute-based access control policies.
 */


data class TenantUpdate (

    /* A descriptive name for the tenant */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* an optional longer description of the tenant */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Arbitraty tenant attributes that will be used to enforce attribute-based access control policies. */
    @Json(name = "attributes")
    val attributes: kotlin.Any? = null

)

