/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Attributes

import com.squareup.moshi.Json

/**
 * 
 *
 * @param roleAssignments 
 * @param attributes 
 */


data class UserData (

    @Json(name = "roleAssignments")
    val roleAssignments: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, Attributes>? = null

)

