/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param key 
 * @param createdAt 
 * @param updatedAt 
 * @param email 
 * @param firstName 
 * @param lastName 
 * @param attributes 
 * @param assignedRoles 
 */


data class UserObject (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "first_name")
    val firstName: kotlin.String? = null,

    @Json(name = "last_name")
    val lastName: kotlin.String? = null,

    @Json(name = "attributes")
    val attributes: kotlin.Any? = null,

    @Json(name = "assigned_roles")
    val assignedRoles: kotlin.collections.List<kotlin.String>? = null

)

